# Bulletproof Project Template build pipeline
variables:
  semver: 0.1.0

trigger:
  tags:
    include:
      - v*

pool:
  vmImage: 'windows-latest'

steps:
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install --production'
  displayName: 'npm install --production'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run read-version'
  displayName: 'run read-version'

- script:
    echo '$(SemVersion)'    