# Bulletproof Project Template build pipeline

trigger:
  tags:
    include:
      - v*

pool:
  vmImage: 'windows-latest'

steps:
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install --production'
  displayName: 'npm install --production'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run read-version'
  displayName: 'run read-version'

- script:
    echo '$(SemVersion)'    