# Bulletproof Project Template build pipeline
variables:
  semver: 0.1.1

# Build Number
name: $(semver)$(Rev:.r)

# Should only trigger master branch or PR's
trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:

- script:
    echo '$(Build.BuildNumber)'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'Solutions/packages.config'
    restoreDirectory: 'packages'

- task: BatchScript@1
  displayName: 'Run spkl pack'
  inputs:
    filename: 'Solutions/spkl/pack.bat'

- task: CopyFiles@2
  displayName: 'Copy Build Artifacts'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: 'Solutions/*.zip'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Solution Artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: Solutions